export const API_URL = import.meta.env.VITE_API_URL;
export const APP_TITLE = import.meta.env.VITE_APP_TITLE;
export const APP_WS_URL = import.meta.env.VITE_WS_URL ;
export const API_ENDPOINTS = {
  login: `${API_URL}/auth/login`,
  register: `${API_URL}/auth/register`,
  logout: `${API_URL}/auth/logout`,
  forgotPassword: `${API_URL}/auth/forgot-password`,
  verifyResetCode: `${API_URL}/auth/verify-reset-code`,
  resetPassword: `${API_URL}/auth/reset-password`,
  upload: `${API_URL}/uploads`,
  ticket: `${API_URL}/tickets`,
  user: `${API_URL}/users`,
  dashboard: `${API_URL}/dashboard`,
  notifications: `${API_URL}/notifications`,
  organisation: `${API_URL}/organisations`,
  serviceCenter: `${API_URL}/service-centers`,
  spareRequest: `${API_URL}/spare-requests`,
  inventory: `${API_URL}/inventory`,
  product: `${API_URL}/products`,
  serviceCenterAssignment: `${API_URL}/service-center-assignment`,
  conversation: `${API_URL}/conversations`,
  milestone: `${API_URL}/milestones`,
  states: `${API_URL}/states`,
  project: `${API_URL}/projects`,
  projectWA: `${API_URL}/projectsWA`,
  organisationsWA: `${API_URL}/organisationsWA`,
  motorhp: `${API_URL}/motorhp`,
  templates: `${API_URL}/templates`,
  settings: `${API_URL}/settings`,
  LMS_BASE_URL: import.meta.env.VITE_LMS_BASE_URL,
};
